name: testemobix
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx:
  flutter_mobx: ^1.0.1
  flushbar: ^1.10.2

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^1.0.2
  build_runner: ^1.8.0

flutter:

  uses-material-design: true
